[package]
name = "tilcayo-auth"
version = "0.1.0"
edition = "2024"

[dependencies]
argon2 = "0.6.0"
thiserror = "2.0.20"
tilcayo-core.workspace = true
tilcayo-db.workspace = true
sqlx = "0.9.0"
jsonwebtoken.workspace = true
serde.workspace = true
getrandom = "0.4.3"
sha2 = "0.11.0"
hex = "0.4.3"
redis = { version = "1.7.0", features = ["tokio-comp"] }

[dev-dependencies]
tokio = { version = "1.53.1", features = ["macros", "rt-multi-thread"] }
