services:
  postgres:
    image: postgres:18
    environment:
      POSTGRES_USER: tilcayo
      POSTGRES_PASSWORD: tilcayo
      POSTGRES_DB: tilcayo
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

  redis:
    image: redis:8
    ports:
      - "6379:6379"

volumes:
  postgres_data:
