[package]
name = "tilcayo-api"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.9"
serde = { workspace = true, features = ["derive"] }
tokio = { version = "1.53.1", features = ["macros", "rt-multi-thread", "net"] }
tilcayo-db.workspace = true
tilcayo-core.workspace = true
tilcayo-auth.workspace = true
sqlx = "0.9.0"
serde_json = "1.0.151"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
dotenvy = "0.15.7"
utoipa = { version = "5.0.0", features = ["axum_extras", "preserve_order"] }
utoipa-swagger-ui = { version = "9.0.2", features = ["axum"] }
