[package]
name = "tilcayo-api"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.9"
serde = { workspace = true, features = ["derive"] }
tokio = { version = "1.53.1", features = ["macros", "rt-multi-thread", "net"] }
tilcayo-db.workspace = true
tilcayo-core.workspace = true
tilcayo-auth.workspace = true
sqlx = "0.9.0"
serde_json = "1.0.151"
